### ISSUE TITLE
grimshot copy area: no longer highlights selection area

### ISSUE THREAD

**Issue by evils** [OctopusET/sway-contrib#27]
i can't quite pin down what change caused this
but somewhere between 2023-06-30 and 2024-01-20 this behaviour changed
originally reported here: https://github.com/NixOS/nixpkgs/pull/283388#issuecomment-1912914883

the screen still gets the white haze, and selection still kinda works, but the area selected is not highlighted by clearing the haze
and shaking my cursor around wildly while selecting results in `selection cancelled`
it does appear that if i hold my mouse button and wait at least 2 seconds after making the selection, it is highlighted
once that highlighting is active, shaking the mouse with the button held, does not cancel the selection

besides a bit of a flicker of the white haze going on, then off when the window is selected, to back on when area selection is started
the `anything` option is functionally equivalent to the old `area` feature, maybe it should just be made an alias of `anything`?

**Comment by evils** [comment]
seems to have resolved itself after updating and restarting my OS...

**Comment by OctopusET** [comment]
I also tested, works as intended.
Still, thanks for the issue report.
